# Generated by Django 6.0.7 on 2026-07-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_attributevalue_attribute_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='variantattributevalue',
            name='unique_variant_attribute',
        ),
        migrations.AddConstraint(
            model_name='variantattributevalue',
            constraint=models.UniqueConstraint(fields=('variant', 'attribute_value'), name='unique_variant_attribute_value'),
        ),
        migrations.RemoveField(
            model_name='variantattributevalue',
            name='attribute',
        ),
    ]
